services:
  twitter_clone_api:
    container_name: twitter_app
    build: .
    ports:
      - "5000:8000"
    volumes:
      - .:/TwitterCloneAPI
    depends_on:
      - twitter_clone_db
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
  twitter_clone_db:
    container_name: twitter_clone_db
    image: postgres:16
    expose:
        - ${DB_PORT}
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - twitterclone_db_data:/var/lib/postgresql/data
volumes:
  twitterclone_db_data:

